name: 水卡数据生成器

on:
  workflow_dispatch:
    inputs:
      balance:
        description: "金额 (0-655.35元)"
        required: true
        type: string
      usage_count:
        description: "使用次数 (0-255次，留空则随机)"
        required: false
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: 调试信息
        run: |
          echo "当前工作目录: $(pwd)"
          ls -la
          echo "Python版本: $(python --version)"
          echo "Pip版本: $(pip --version)"
          
      - name: 计算数据块
        id: calculation
        run: |
          # 确保脚本存在
          if [ ! -f "exploit.py" ]; then
            echo "错误: exploit.py 文件不存在!"
            exit 1
          fi
          
          # 添加执行权限
          chmod +x exploit.py
          
          # 构建命令参数
          CMD="python exploit.py ${{ github.event.inputs.balance }}"
          if [ -n "${{ github.event.inputs.usage_count }}" ]; then
            CMD="$CMD ${{ github.event.inputs.usage_count }}"
          fi
          
          echo "执行命令: $CMD"
          
          # 执行并捕获输出
          OUTPUT=$($CMD 2>&1)
          EXIT_CODE=$?
          
          if [ $EXIT_CODE -ne 0 ]; then
            echo "脚本执行失败，错误代码: $EXIT_CODE"
            echo "错误输出: $OUTPUT"
            exit 1
          fi
          
          echo "脚本输出: $OUTPUT"
          echo "RESULT=$OUTPUT" >> $GITHUB_OUTPUT
          
      - name: 生成报告
        if: success()
        run: |
          echo "正在生成报告..."
          cat << EOF > report.txt
          ╔══════════════════════════╗
          ║      水卡数据生成结果      ║
          ╠═══════════════╦══════════╣
          ║ 设置金额      ║ ${{ github.event.inputs.balance }}元 ║
          ╠═══════════════╬══════════╣
          ║ 使用次数      ║ ${{ github.event.inputs.usage_count || '随机' }}次 ║
          ╠═══════════════╩══════════╣
          ║ 生成的数据块：            ║
          ║ ${{ steps.calculation.outputs.RESULT }} ║
          ╚══════════════════════════╝
          EOF
          echo "报告生成完成"
          
      - name: 上传结果
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: 水卡数据结果
          path: report.txt
