name: Water Card Data Generator

on:
  workflow_dispatch:
    inputs:
      balance:
        description: "金额 (0-655.35元)"
        required: true
        type: string
      usage_count:
        description: "使用次数 (0-255次，留空则随机)"
        required: false
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Calculate data block
        id: calc
        run: |
          if [ -z "${{ inputs.usage_count }}" ]; then
            python exploit.py "${{ inputs.balance }}"
          else
            python exploit.py "${{ inputs.balance }}" "${{ inputs.usage_count }}"
          fi
          echo "RESULT=$(python exploit.py "${{ inputs.balance }}" ${{ inputs.usage_count || '' }})" >> $GITHUB_OUTPUT
          
      - name: Generate report
        run: |
          cat << 'EOF' > report.txt
          ╔══════════════════════════╗
          ║     Water Card Result    ║
          ╠═══════════════╦══════════╣
          ║ Balance       ║ ${{ inputs.balance }} ¥ ║
          ╠═══════════════╬══════════╣
          ║ Usage Count   ║ ${{ inputs.usage_count || 'Random' }} ║
          ╠═══════════════╩══════════╣
          ║ Data Block:             ║
          ║ ${{ steps.calc.outputs.RESULT }} ║
          ╚══════════════════════════╝
          EOF
          
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: water-card-data
          path: report.txt
