name: 水卡数据生成器

on:
  workflow_dispatch:
    inputs:
      balance:
        description: "金额 (0-655.35元)"
        required: true
        type: string
      usage_count:
        description: "使用次数 (0-255次，留空则随机)"
        required: false
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: 计算数据块
        id: calculation
        run: |
          if [ -z "${{ inputs.usage_count }}" ]; then
            python exploit.py "${{ inputs.balance }}"
          else
            python exploit.py "${{ inputs.balance }}" "${{ inputs.usage_count }}"
          fi
          echo "RESULT=$(python exploit.py "${{ inputs.balance }}" ${{ inputs.usage_count || '' }})" >> $GITHUB_OUTPUT
          
      - name: 生成报告
        run: |
          cat << 'EOF' > report.txt
          ╔══════════════════════════╗
          ║      水卡数据生成结果      ║
          ╠═══════════════╦══════════╣
          ║ 设置金额      ║ ${{ inputs.balance }}元 ║
          ╠═══════════════╬══════════╣
          ║ 使用次数      ║ ${{ inputs.usage_count || '随机' }}次 ║
          ╠═══════════════╩══════════╣
          ║ 生成的数据块：            ║
          ║ ${{ steps.calculation.outputs.RESULT }} ║
          ╚══════════════════════════╝
          EOF
          
      - name: 上传结果
        uses: actions/upload-artifact@v4
        with:
          name: 水卡数据结果
          path: report.txt
