name: 水卡数据生成器

on:
  workflow_dispatch:
    inputs:
      balance:
        description: "金额 (0-655.35元)"
        required: true
        type: string
      usage_count:
        description: "使用次数 (0-255次，留空则随机)"
        required: false
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: 安装依赖
        run: pip install pycryptodome  # 添加可能需要的依赖
          
      - name: 计算数据块
        id: calculation
        run: |
          # 调试：显示当前目录内容
          ls -la
          
          # 确保脚本可执行
          chmod +x exploit.py
          
          # 处理参数传递
          if [ -z "${{ github.event.inputs.usage_count }}" ]; then
            echo "执行命令: python exploit.py ${{ github.event.inputs.balance }}"
            OUTPUT=$(python exploit.py "${{ github.event.inputs.balance }}")
          else
            echo "执行命令: python exploit.py ${{ github.event.inputs.balance }} ${{ github.event.inputs.usage_count }}"
            OUTPUT=$(python exploit.py "${{ github.event.inputs.balance }}" "${{ github.event.inputs.usage_count }}")
          fi
          
          # 检查命令是否成功执行
          if [ $? -ne 0 ]; then
            echo "错误：脚本执行失败"
            exit 1
          fi
          
          echo "生成结果: ${OUTPUT}"
          echo "RESULT=${OUTPUT}" >> $GITHUB_OUTPUT
          
      - name: 生成报告
        if: success()
        run: |
          cat << EOF > report.txt
          ╔══════════════════════════╗
          ║      水卡数据生成结果      ║
          ╠═══════════════╦══════════╣
          ║ 设置金额      ║ ${{ github.event.inputs.balance }}元 ║
          ╠═══════════════╬══════════╣
          ║ 使用次数      ║ ${{ github.event.inputs.usage_count || '随机' }}次 ║
          ╠═══════════════╩══════════╣
          ║ 生成的数据块：            ║
          ║ ${{ steps.calculation.outputs.RESULT }} ║
          ╚══════════════════════════╝
          EOF
          
      - name: 上传结果
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: 水卡数据结果
          path: report.txt
