name: 水卡数据生成器
on:
  workflow_dispatch:
    inputs:
      balance:655.35
        description: '金额 (0-655.35元)'
        required: true
        type: string
      usage_count:
        description: '使用次数 (0-255次，留空则随机)'
        required: false
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 计算数据块
        id: calculation
        run: |
          if [ -z "${{ github.event.inputs.usage_count }}" ]; then
            python exploit.py "${{ github.event.inputs.balance }}"
          else
            python exploit.py "${{ github.event.inputs.balance }}" "${{ github.event.inputs.usage_count }}"
          fi
          echo "RESULT=$(python exploit.py "${{ github.event.inputs.balance }}" ${{ github.event.inputs.usage_count || '' }})" >> $GITHUB_OUTPUT
          
      - name: 生成报告
        run: |
          printf '%s\n' \
          "╔══════════════════════════╗" \
          "║      水卡数据生成结果      ║" \
          "╠═══════════════╦══════════╣" \
          "║ 设置金额      ║ ${{ github.event.inputs.balance }}元 ║" \
          "╠═══════════════╬══════════╣" \
          "║ 使用次数      ║ ${{ github.event.inputs.usage_count || '随机' }}次 ║" \
          "╠═══════════════╩══════════╣" \
          "║ 生成的数据块：            ║" \
          "║ ${{ steps.calculation.outputs.RESULT }} ║" \
          "╚══════════════════════════╝" > report.txt
          
      - name: 上传结果
        uses: actions/upload-artifact@v3
        with:
          name: 水卡数据结果
          path: report.txt
